/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(admin)'}/notifications` | `/notifications`; params?: Router.UnknownInputParams; } | { pathname: `${'/(admin)'}/upload` | `/upload`; params?: Router.UnknownInputParams; } | { pathname: `${'/(admin)'}/users` | `/users`; params?: Router.UnknownInputParams; } | { pathname: `${'/(fos)'}/search` | `/search`; params?: Router.UnknownInputParams; } | { pathname: `${'/(repo)'}/search` | `/search`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } } | { pathname: `/allocation/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/repo-allocation/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/login`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(admin)'}/notifications` | `/notifications`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(admin)'}/upload` | `/upload`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(admin)'}/users` | `/users`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(fos)'}/search` | `/search`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(repo)'}/search` | `/search`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } } | { pathname: `/allocation/[id]`, params: Router.UnknownOutputParams & { id: string; } } | { pathname: `/repo-allocation/[id]`, params: Router.UnknownOutputParams & { id: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(admin)'}/notifications${`?${string}` | `#${string}` | ''}` | `/notifications${`?${string}` | `#${string}` | ''}` | `${'/(admin)'}/upload${`?${string}` | `#${string}` | ''}` | `/upload${`?${string}` | `#${string}` | ''}` | `${'/(admin)'}/users${`?${string}` | `#${string}` | ''}` | `/users${`?${string}` | `#${string}` | ''}` | `${'/(fos)'}/search${`?${string}` | `#${string}` | ''}` | `/search${`?${string}` | `#${string}` | ''}` | `${'/(repo)'}/search${`?${string}` | `#${string}` | ''}` | `/search${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(admin)'}/notifications` | `/notifications`; params?: Router.UnknownInputParams; } | { pathname: `${'/(admin)'}/upload` | `/upload`; params?: Router.UnknownInputParams; } | { pathname: `${'/(admin)'}/users` | `/users`; params?: Router.UnknownInputParams; } | { pathname: `${'/(fos)'}/search` | `/search`; params?: Router.UnknownInputParams; } | { pathname: `${'/(repo)'}/search` | `/search`; params?: Router.UnknownInputParams; } | `/+not-found${`?${string}` | `#${string}` | ''}` | `/allocation/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/repo-allocation/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } } | { pathname: `/allocation/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/repo-allocation/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
    }
  }
}
